### ISSUE TITLE
Activity Diagram

### ISSUE THREAD

**Issue by BalmaBrian** [LiquidPropulsionGroup/EngineWebServer#14]
Simple Activity Diagram to show how v1.0 of the Engine Web Server works.

**Comment by BalmaBrian** [comment]
Activity Diagram Transparent Background
<img src="https://github.com/LiquidPropulsionGroup/EngineWebServer/blob/master/img/Engine%20Web%20Server%20v1.0%20Activity%20Diagram%20~%20Transparent%20Background.png">

**Comment by BalmaBrian** [comment]
Activity Diagram Solid Background
<img src="https://github.com/LiquidPropulsionGroup/EngineWebServer/blob/master/img/Engine%20Web%20Server%20v1.0%20Activity%20Diagram%20~%20Solid%20Background.png">

**Comment by BalmaBrian** [comment]
@M-LKT  @chubbychow What do yall think? Also the images should be posted on the Discord.

**Comment by TWCCarlson** [comment]
Controller has 2 l's
Image embeds on GitHub seem to be broken?
Should GUI requests get a separate diagram?

**Comment by BalmaBrian** [comment]
@TWCCarlson  
- This activity diagram dose not break down the UI because this repo is not the UI repo.
- Spelling errors fixed
- png's seem not to work well in issues

**Comment by TWCCarlson** [comment]
Requests from the GUI to retrieve information are being handled by the webserver are they not?

**Comment by BalmaBrian** [comment]
Basic Activity Diagram for Engine Web Server v1.0 done.
