### ISSUE TITLE
UART research

### ISSUE THREAD

**Issue by BalmaBrian** [LiquidPropulsionGroup/EngineWebServer#7]
I want to look into raspberry pie and Arduino communication through UART. This is the article I have on the topic so far https://roboticsbackend.com/raspberry-pi-arduino-serial-communication/

**Comment by Maarten-Baert** [comment]
Hello,
If you can get your hands on a (digital) copy of "Make: AVR Programming" by Elliot Williams, that one is a good read in general in my opinion. 
It has a couple of chapters that go into detail about UART (Serial I/O) for the Atmel AVR microcontroller (used in Arduino but programmed in C in the book) and a lot of other things as well. 
Hope this is useful.

**Comment by BalmaBrian** [comment]
@Maarten-Baert Thanks for the info, this will make this weekends programming a little more manageable.

**Comment by BalmaBrian** [comment]
Terminal access through UART: [YouTube Link](https://www.youtube.com/watch?v=ZRKBlGvsxMw)
Basically what our REST server dose: [YouTube Link](https://www.youtube.com/watch?v=e38T-6C3mqk)

**Comment by BalmaBrian** [comment]
This npm package might be what we go with for UART Serial Communication. [link](https://www.npmjs.com/package/serialport)

**Comment by BalmaBrian** [comment]
We are going to throw this on the back burner.
