### ISSUE TITLE
Engine Web Server Wiki

### ISSUE THREAD

**Issue by BalmaBrian** [LiquidPropulsionGroup/EngineWebServer#8]
### Finish writing the first part of the wiki

Wiki Pages to be written:

- [x] Setting up the Raspberry Pi 
- [x] Installing Raspberry Pi OS
- [x] Setting up SSH and optionally Wi-Fi
- [x] SSHing into the Raspberry Pi
- [x] Enabling SSH Server
- [x] Installing Environments

**Comment by BalmaBrian** [comment]
[Setting up the Raspberry Pi](https://github.com/LiquidPropulsionGroup/EngineWebServer/wiki/Setting-up-the-Raspberry-Pi) done

**Comment by BalmaBrian** [comment]
[Installing Raspberry Pi OS](https://github.com/LiquidPropulsionGroup/EngineWebServer/wiki/Installing-Raspberry-Pi-OS) done

**Comment by chubbychow** [comment]
this is an article on how to connect via ssh using rasberry pi.   [url](https://www.raspberrypi.org/documentation/remote-access/ssh/windows10.md)

**Comment by BalmaBrian** [comment]
img directory created in [this is the commit](335391744a4123be38cc510a349a5accdf8cfcb4). Screen shots and wiki pictures are put there for reference in page creation.

**Comment by BalmaBrian** [comment]
Video made for wiki
[![asciicast](https://asciinema.org/a/vRajSNR9l2dI6HlO8CkysG5FC.svg)](https://asciinema.org/a/vRajSNR9l2dI6HlO8CkysG5FC)

**Comment by BalmaBrian** [comment]
Steps for the `Setting up SSH and optionally Wi-Fi` page:

1. make ssh file somewhere (not boot on sd card)
2. make wpa_supplicant.json on boot on sd card
3. populate wpa_supplicant.json
4. power your board
5. locate your boards ip
6. ssh into your board
7. credentials for your pi

**Comment by BalmaBrian** [comment]
screen cap converted into gif
![](https://media.giphy.com/media/XHmesuXqGgr4E0ox0Q/giphy.gif)

**Comment by BalmaBrian** [comment]
new screen cap
![](https://media.giphy.com/media/aPICjLeRxyeCQCZamJ/giphy.gif)

**Comment by BalmaBrian** [comment]
[SSHing into the Raspberry Pi](https://github.com/LiquidPropulsionGroup/EngineWebServer/wiki/SSHing-into-the-Raspberry-Pi) page done.

**Comment by BalmaBrian** [comment]
[Setting up SSH and Optionally Wi-Fi](https://github.com/LiquidPropulsionGroup/EngineWebServer/wiki/Setting-up-SSH-and-optinally-Wi-Fi) Done.

**Comment by BalmaBrian** [comment]
[Installing Environments](https://github.com/LiquidPropulsionGroup/EngineWebServer/wiki/Installing-Environments) Done.

**Comment by BalmaBrian** [comment]
Final page [Enabling SSH Server](https://github.com/LiquidPropulsionGroup/EngineWebServer/wiki/Enabling-SSH-Server) Done.
